import { Inter } from "next/font/google";
import { GlobalContextProvider } from "@/context/store";
import { getStocks } from "@/utils/getStocks";

import "./globals.css";
import styles from "./globals.module.scss";

export const metadata = {
  title: {
    default: "RTDA",
    template: "%s - Real Time Data",
  },
  description: "Generated by create next app",
  twitter: {
    card: "summary_large_image",
  },
};

export default async function RootLayout({ children }) {
  // const handleStocksUpdate = (stocks) => {
  //   console.log(stocks, "Updated Stocks:");
  // };

  // const closeWebSocket = getStocks(handleStocksUpdate);

  const stocks = [];

  return (
    <html lang="en">
      <body className={styles.body}>
        <div className={styles.body__content}>
          <GlobalContextProvider serverSideStocksData={stocks}>
            {children}
          </GlobalContextProvider>
        </div>
      </body>
    </html>
  );
}
