import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalContextProvider } from "@/context/store";
import { getStocks } from "@/utils/getStocks";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "RTDA",
    template: "%s - Real Time Data",
  },
  description: "Generated by create next app",
  twitter: {
    card: "summary_large_image",
  },
};

export default async function RootLayout({ children }) {
  // const handleStocksUpdate = (stocks) => {
  //   console.log(stocks, "Updated Stocks:");
  // };

  // const closeWebSocket = getStocks(handleStocksUpdate);

  const stocks = [];

  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContextProvider serverSideStocksData={stocks}>
          {children}
        </GlobalContextProvider>
      </body>
    </html>
  );
}
