import { GlobalContextProvider } from "@/context/store";

import "./globals.css";
import styles from "./globals.module.scss";

// export const metadata = {
//   title: {
//     default: "RTDA",
//     template: "%s - Real Time Data",
//   },
//   description: "Generated by create next app",
//   twitter: {
//     card: "summary_large_image",
//   },
// };

export default async function RootLayout({ children }) {
  const stocksData = [];
  return (
    <html lang="en">
      <body className={styles.body}>
        <div className={styles.body__content}>
          <GlobalContextProvider serverSideStocksData={stocksData}>
            {children}
          </GlobalContextProvider>
        </div>
      </body>
    </html>
  );
}
