// Mock stock data
const stocks = [
  {
    id: 1,
    symbol: "AAPL",
    companyName: "Apple Inc.",
    location: "Cupertino, California",
    address: "One Apple Park Way",
    price: 150.45,
    profit: 1000000,
    loss: 500000,
  },
  {
    id: 2,
    symbol: "GOOG",
    companyName: "Alphabet Inc.",
    location: "Mountain View, California",
    address: "1600 Amphitheatre Parkway",
    price: 2500.3,
    profit: 1500000,
    loss: 700000,
  },
  {
    id: 3,
    symbol: "MSFT",
    companyName: "Microsoft Corporation",
    location: "Redmond, Washington",
    address: "One Microsoft Way",
    price: 300.2,
    profit: 1200000,
    loss: 600000,
  },
  {
    id: 4,
    symbol: "AMZN",
    companyName: "Amazon.com, Inc.",
    location: "Seattle, Washington",
    address: "410 Terry Avenue North",
    price: 3500.99,
    profit: 2000000,
    loss: 800000,
  },
  {
    id: 5,
    symbol: "TSLA",
    companyName: "Tesla, Inc.",
    location: "Palo Alto, California",
    address: "3500 Deer Creek Road",
    price: 900.75,
    profit: 1800000,
    loss: 900000,
  },
  {
    id: 6,
    symbol: "FB",
    companyName: "Meta Platforms, Inc.",
    location: "Menlo Park, California",
    address: "1 Hacker Way",
    price: 300.55,
    profit: 900000,
    loss: 400000,
  },
  {
    id: 7,
    symbol: "NFLX",
    companyName: "Netflix, Inc.",
    location: "Los Gatos, California",
    address: "100 Winchester Circle",
    price: 550.45,
    profit: 1100000,
    loss: 300000,
  },
  {
    id: 8,
    symbol: "NVDA",
    companyName: "NVIDIA Corporation",
    location: "Santa Clara, California",
    address: "2788 San Tomas Expressway",
    price: 750.25,
    profit: 1300000,
    loss: 400000,
  },
  {
    id: 9,
    symbol: "PYPL",
    companyName: "PayPal Holdings, Inc.",
    location: "San Jose, California",
    address: "2211 North First Street",
    price: 300.99,
    profit: 800000,
    loss: 200000,
  },
  {
    id: 10,
    symbol: "INTC",
    companyName: "Intel Corporation",
    location: "Santa Clara, California",
    address: "2200 Mission College Boulevard",
    price: 55.8,
    profit: 600000,
    loss: 300000,
  },
  {
    id: 11,
    symbol: "IBM",
    companyName: "International Business Machines Corporation",
    location: "Armonk, New York",
    address: "1 New Orchard Road",
    price: 125.35,
    profit: 800000,
    loss: 400000,
  },
  {
    id: 12,
    symbol: "CSCO",
    companyName: "Cisco Systems, Inc.",
    location: "San Jose, California",
    address: "170 West Tasman Drive",
    price: 55.25,
    profit: 500000,
    loss: 300000,
  },
  {
    id: 13,
    symbol: "QCOM",
    companyName: "Qualcomm Incorporated",
    location: "San Diego, California",
    address: "5775 Morehouse Drive",
    price: 150.8,
    profit: 900000,
    loss: 500000,
  },
  {
    id: 14,
    symbol: "ORCL",
    companyName: "Oracle Corporation",
    location: "Redwood City, California",
    address: "500 Oracle Parkway",
    price: 75.65,
    profit: 700000,
    loss: 400000,
  },
  {
    id: 15,
    symbol: "CRM",
    companyName: "Salesforce.com, Inc.",
    location: "San Francisco, California",
    address: "415 Mission Street",
    price: 225.4,
    profit: 1000000,
    loss: 600000,
  },
  {
    id: 16,
    symbol: "JPM",
    companyName: "JPMorgan Chase & Co.",
    location: "New York, New York",
    address: "383 Madison Avenue",
    price: 145.75,
    profit: 1200000,
    loss: 700000,
  },
  {
    id: 17,
    symbol: "V",
    companyName: "Visa Inc.",
    location: "Foster City, California",
    address: "900 Metro Center Boulevard",
    price: 200.9,
    profit: 1100000,
    loss: 600000,
  },
  {
    id: 18,
    symbol: "DIS",
    companyName: "The Walt Disney Company",
    location: "Burbank, California",
    address: "500 South Buena Vista Street",
    price: 150.2,
    profit: 900000,
    loss: 400000,
  },
  {
    id: 19,
    symbol: "BP",
    companyName: "BP plc",
    location: "London, United Kingdom",
    address: "1 St James's Square",
    price: 25.6,
    profit: 300000,
    loss: 200000,
  },
  {
    id: 20,
    symbol: "WMT",
    companyName: "Walmart Inc.",
    location: "Bentonville, Arkansas",
    address: "702 Southwest 8th Street",
    price: 140.85,
    profit: 1500000,
    loss: 800000,
  },
];

// Export the stocks array
module.exports = stocks;
